version: '3.3'

services:
   db:
     image: vishnusaisankeerth/br:sqlimg
     container_name: brsql_container
     volumes:
       - /opt/data:/var/lib/mysql
     restart: always
     environment:
       MYSQL_ROOT_PASSWORD: admin
       MYSQL_DATABASE: student_info
       MYSQL_USER: root
     ports:
        - "3310:3306"

   webapi:
     depends_on:
       - db
     image: vishnusaisankeerth/br:apiimg
     container_name: brproject_container
     hostname: project_api
     ports:
       - "9000:8080"
     restart: always
     volumes:
       - ./myelk/logs/input.out:/tmp/input.out
       
    
