version: '3.3'

services:
   db:
     image: projectmysql
     container_name: sql_container
     volumes:
       - /opt/data:/var/lib/mysql
     restart: always
     environment:
       MYSQL_ROOT_PASSWORD: admin
       MYSQL_DATABASE: student_info
       MYSQL_USER: root

   webapi:
     depends_on:
       - db
     image: project 
     container_name: project_container
     hostname: project_api
     ports:
       - "9000:8080"
     restart: always