version: '3.3'

services:
   db:
     image: vishnusaisankeerth/br:sqlimg
     volumes:
       - /opt/data:/var/lib/mysql
       - /etc/timezone:/etc/timezone:ro
       - /etc/localtime:/etc/localtime:ro
     restart: always
     environment:
       MYSQL_ROOT_PASSWORD: admin
       MYSQL_DATABASE: student_info
       MYSQL_USER: root

   webapi:
     depends_on:
       - db
     image: vishnusaisankeerth/br:apiimg
     container_name: brproject_container
     volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
     hostname: project_api
     ports:
       - "9000:8080"
     restart: always